name: Deploy

on:
  push:
    branches:
      - master
      - staging
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false # Skip loading submodules

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Create env file
        run: |
          touch .env.production
          echo "GOOGLE_SHEET_API_KEY=${{ secrets.GOOGLE_SHEET_API_KEY }}" >> .env.production
          echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> .env.production
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.production
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.production
          echo "GOOGLE_REFRESH_TOKEN=${{ secrets.GOOGLE_REFRESH_TOKEN }}" >> .env.production
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env.production
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env.production
          echo "MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}" >> .env.production
          echo "OPENCHAT_API_KEY=${{ secrets.OPENCHAT_API_KEY }}" >> .env.production
          echo "PERFLEXITY_API_KEY=${{ secrets.PERFLEXITY_API_KEY }}" >> .env.production
          echo "GITHUB_CLIENT_ID=${{ secrets.GH_CLIENT_ID }}" >> .env.production
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL}}" >> .env.production
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY}}" >> .env.production
          echo "CUSTOM_DOMAIN=${{ secrets.CUSTOM_DOMAIN }}" >> .env.production

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run build
          echo "${{ github.ref }}"  # Check running branch

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
          cname: ${{ github.ref == 'refs/heads/master' && 'interview.hoanghuyduc.com' || 'staging.interview.hoanghuyduc.com' }}

      - name: Send Telegram Message
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d '{
                  "chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}",
                  "text": "🚀 CI/CD chạy xong!\n📝 Commit: ${{ github.event.head_commit.message }}\n🔗 Repo: ${{ github.repository }}",
                  "parse_mode": "Markdown"
                }'
